### ISSUE TITLE
File naming conventions

### ISSUE THREAD

**Issue by WaltGurley** [ncsu-libraries-data-vis/introduction-to-programming-with-python#2]
Improve readability of files by renaming filled versions of notebooks with "filled" at beginning of file, not at end, e.g.:

Yes: filled_Introduction_to_Programming_with_Python_3.ipynb 
No: Introduction_to_Programming_with_Python_3_filled.ipynb

@clairecahoon sound good?

**Comment by clairecahoon** [comment]
Sounds good to me, good idea!

**Comment by WaltGurley** [comment]
Done!
